### ISSUE TITLE
deprecated gtk warning

### ISSUE THREAD

**Issue by tromey** [tromey/gdb-gui#30]
Josh reported:

<jistone> gdb-gui/gui/startup.py:78: Warning: The property
      GtkToolButton:stock-id is deprecated and shouldn't be used
      anymore. It will be removed in a future version.

**Comment by cuviper** [comment]
That's on Fedora 22 with GTK 3.16.  According to [docs](https://developer.gnome.org/gtk3/stable/GtkToolButton.html#GtkToolButton--stock-id) it's been deprecated since 3.10.
